name: Install the dotfile

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  shellcheck:
    name: Shellcheck
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
        with:
          scandir: "./"
  install:
    name: Install
    runs-on: macos-14
    needs: 
      - shellcheck
    steps:
      - uses: actions/checkout@v4
      - name: Execute
        run: ./main.sh